"""baseline

Revision ID: 1cfc95e31a13
Revises: 
Create Date: 2026-07-07 08:26:49.765185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1cfc95e31a13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fec_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('party', sa.String(length=4), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('office', sa.String(length=1), nullable=False),
    sa.Column('incumbent_challenge', sa.String(length=1), nullable=True),
    sa.Column('primary_date', sa.Date(), nullable=True),
    sa.Column('primary_status', sa.String(), nullable=True),
    sa.Column('general_status', sa.String(), nullable=True),
    sa.Column('fundraising_total', sa.Float(), nullable=True),
    sa.Column('cook_rating', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fec_id')
    )
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_table('climate_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eonet_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('magnitude_unit', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eonet_id')
    )
    op.create_index(op.f('ix_climate_events_id'), 'climate_events', ['id'], unique=False)
    op.create_table('competitive_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('cook_rating', sa.String(), nullable=True),
    sa.Column('dem_2024', sa.Float(), nullable=True),
    sa.Column('rep_2024', sa.Float(), nullable=True),
    sa.Column('margin_2024', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('incumbent_party', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitive_districts_id'), 'competitive_districts', ['id'], unique=False)
    op.create_table('earthquakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usgs_id', sa.String(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('depth_km', sa.Float(), nullable=True),
    sa.Column('alert_level', sa.String(), nullable=True),
    sa.Column('tsunami', sa.Boolean(), nullable=False),
    sa.Column('felt', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usgs_id')
    )
    op.create_index(op.f('ix_earthquakes_id'), 'earthquakes', ['id'], unique=False)
    op.create_table('econ_yougov_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('sample_desc', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index(op.f('ix_econ_yougov_reports_id'), 'econ_yougov_reports', ['id'], unique=False)
    op.create_table('house_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('pollster', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('population', sa.String(length=4), nullable=True),
    sa.Column('dem', sa.Float(), nullable=True),
    sa.Column('rep', sa.Float(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id')
    )
    op.create_index(op.f('ix_house_polls_id'), 'house_polls', ['id'], unique=False)
    op.create_table('house_retirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(), nullable=False),
    sa.Column('party', sa.String(length=1), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_retirements_id'), 'house_retirements', ['id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'url', name='news_articles_category_url_key')
    )
    op.create_table('nws_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nws_id', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('area_desc', sa.String(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('wfo_url', sa.String(), nullable=True),
    sa.Column('onset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nws_id')
    )
    op.create_index(op.f('ix_nws_alerts_id'), 'nws_alerts', ['id'], unique=False)
    op.create_table('prediction_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('event_title', sa.String(), nullable=True),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('yes_price', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'market_id', name='uq_market_platform_id')
    )
    op.create_index(op.f('ix_prediction_markets_id'), 'prediction_markets', ['id'], unique=False)
    op.create_table('regional_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temp_max_f', sa.Float(), nullable=True),
    sa.Column('temp_min_f', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region')
    )
    op.create_table('service_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trend_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_clusters_id'), 'trend_clusters', ['id'], unique=False)
    op.create_table('votehub_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('votehub_id', sa.String(), nullable=False),
    sa.Column('poll_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('pollster', sa.String(), nullable=True),
    sa.Column('sponsors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('population', sa.String(length=4), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approve', sa.Float(), nullable=True),
    sa.Column('disapprove', sa.Float(), nullable=True),
    sa.Column('dem', sa.Float(), nullable=True),
    sa.Column('rep', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('votehub_id')
    )
    op.create_index(op.f('ix_votehub_polls_id'), 'votehub_polls', ['id'], unique=False)
    op.create_index(op.f('ix_votehub_polls_poll_type'), 'votehub_polls', ['poll_type'], unique=False)
    op.create_table('candidate_issue_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('issue_code', sa.String(), nullable=False),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('supporting_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_issue_tags_id'), 'candidate_issue_tags', ['id'], unique=False)
    op.create_table('econ_yougov_crosstabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(), nullable=True),
    sa.Column('question_key', sa.String(), nullable=False),
    sa.Column('question_title', sa.String(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['econ_yougov_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_econ_yougov_crosstabs_id'), 'econ_yougov_crosstabs', ['id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('yes_price', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['prediction_markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_id'), 'market_snapshots', ['id'], unique=False)
    op.create_table('trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('traffic_volume', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appearance_count', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('velocity_abs', sa.Integer(), nullable=False),
    sa.Column('velocity_pct', sa.Integer(), nullable=False),
    sa.Column('rank_velocity', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=False),
    sa.Column('sources_list', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('trend_window', sa.String(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('geo', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['trend_clusters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trends_id'), 'trends', ['id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trend_id')
    )
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('traffic_volume', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_snapshots_id'), 'trend_snapshots', ['id'], unique=False)
    op.create_table('wiki_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extract', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('search_rank', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_pages_id'), 'wiki_pages', ['id'], unique=False)
    op.create_table('wiki_pageviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wiki_page_id', sa.Integer(), nullable=False),
    sa.Column('view_date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wiki_page_id'], ['wiki_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_pageviews_id'), 'wiki_pageviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wiki_pageviews_id'), table_name='wiki_pageviews')
    op.drop_table('wiki_pageviews')
    op.drop_index(op.f('ix_wiki_pages_id'), table_name='wiki_pages')
    op.drop_table('wiki_pages')
    op.drop_index(op.f('ix_trend_snapshots_id'), table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_trends_id'), table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_market_snapshots_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_econ_yougov_crosstabs_id'), table_name='econ_yougov_crosstabs')
    op.drop_table('econ_yougov_crosstabs')
    op.drop_index(op.f('ix_candidate_issue_tags_id'), table_name='candidate_issue_tags')
    op.drop_table('candidate_issue_tags')
    op.drop_index(op.f('ix_votehub_polls_poll_type'), table_name='votehub_polls')
    op.drop_index(op.f('ix_votehub_polls_id'), table_name='votehub_polls')
    op.drop_table('votehub_polls')
    op.drop_index(op.f('ix_trend_clusters_id'), table_name='trend_clusters')
    op.drop_table('trend_clusters')
    op.drop_table('service_status')
    op.drop_table('regional_weather')
    op.drop_index(op.f('ix_prediction_markets_id'), table_name='prediction_markets')
    op.drop_table('prediction_markets')
    op.drop_index(op.f('ix_nws_alerts_id'), table_name='nws_alerts')
    op.drop_table('nws_alerts')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_house_retirements_id'), table_name='house_retirements')
    op.drop_table('house_retirements')
    op.drop_index(op.f('ix_house_polls_id'), table_name='house_polls')
    op.drop_table('house_polls')
    op.drop_index(op.f('ix_econ_yougov_reports_id'), table_name='econ_yougov_reports')
    op.drop_table('econ_yougov_reports')
    op.drop_index(op.f('ix_earthquakes_id'), table_name='earthquakes')
    op.drop_table('earthquakes')
    op.drop_index(op.f('ix_competitive_districts_id'), table_name='competitive_districts')
    op.drop_table('competitive_districts')
    op.drop_index(op.f('ix_climate_events_id'), table_name='climate_events')
    op.drop_table('climate_events')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
